- name: "install nginx and run"
  hosts: app
  become: yes
  tasks:
    - name: "install Nginx"
      ansible.builtin.package: #heterogeneous module that can work for all distributions
        name: "nginx"
        state: "present"
    - name: "start the nginx service"
      absible.builtin.service:
        name: "nginx"
        state: "started"