- name: "install nginx and run"
  hosts: app
  tasks:
    - name: "install Nginx"
      ansible.builtin.package: #heterogeneous module that can work for all distributions
        name: "nginx"
        state: "present"