- name: print the vars
  hosts: app
  vars:
    course: "devops with aws"
    duration: "120hrs"
    trainer: "shiva"
  tasks:
  - name: printing info
    ansible.builtin.debug:
      msg: "Hello, I'm Learning {{course}}, duration is: {{duration}} trainer is {{trainer}}"