- name: task variables
  hosts: app
  vars:
    course: devops with aws from task
    duration: 120hrs
    trainer: shiva
  tasks:
  - name: printing the task vars
    vars:
      course: devops with aws from task
      duration: 120hrs
      trainer: shiva
