- name: print variable from file
  hosts: app
  vars_files:
    -vars.yaml
  tasks:
  - name: getting var file values
    ansible.builtin.debug:
      msg: "hello, i'm taken course on {{course}}. course duration is: {{duration}} , trainer is {{trainer}}"