- name: vars fromm prompt
  hosts: app
  vars_prompt:
  - name: course
    prompt: "please enter course name:"
    private: false
  - name: duration
    prompt: "please enter course duration: "
    private: false
  - name: trainer
    prompt: "please enter course trainer"
  tasks:
  - namw: printing vars from prompt
    ansible.builtin.debug:
      msg: "hello, i'm taken course on {{course}}. course duration is: {{duration}} , trainer is {{trainer}}"