- name: vars preference task
  hosts: app
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: course
  #   prompt: "Enter the course name: "
  # - name: duration
  #   prompt: "enter course duration: "
  # - name: trainer
  #   prompt: "enter trainer name: "
  # vars:
  #   course: "devops with aws playbook"
  #   duration: "120hrs"
  #   trainer: "shiva"
  tasks:
  - name: checking which vars are first preference
    # vars:
    #   course: devops with aws from task
    #   duration: 120hrs
    #   trainer: shiva
    ansible.builtin.debug:
      msg: "hello, i'm taken course on {{course}}. course duration is: {{duration}} , trainer is {{trainer}}"