- name: nginx installing
  hosts : app
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: ngnix
      state: present
  tasks:
  - name: starting nginx service
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes