- name: variable
  hosts: app
  vars_files:
  - var2.yaml
  vars:
    place: charminar
    city: hyderabad
  tasks:
  - name: using variables
    ansible.builtin.debug:
      msg: "{{place}} is located in {{city}}"