- name: print conditions
  hosts: local
  connection: local
  # vars_prompt:
  # - name: number
  #   prompt: "Please enter number"
  #   private: false
  vars:
    number: 54
  tasks:
  - name: print the number
    ansible.builtin.debug:
      msg : "The selected number {{number}} is less than 20"
    when: number | int < 20

  - name: print the highest number
    ansible.builtin.debug:
      msg: "the selected number {{number}} is greater than 20"
    when: number | int >= 20