- name: print conditions
  hosts: local
  connection: local
  vars_prompt:
  - number: number
    prompt: "Please enter number : "
    private: false
  tasks:
  - name: print the number
    ansible.builtin.debug:
    msg : "The selected number : {{number}} is less than 20"
    when: number < 20

  - name: print the highest number
    ansible.builtin.debug:
    msg: "the selected number: {{number}}" is greater than 20"
    when: number => 20