- name: printing loops
  hosts: local
  connection: local
  tasks:
  - name: loops
    ansible.builtin.debug:
      msg: "i love {{item}}"
    loop:
    - apple
    - grape
    - mango
    - orange
    - guvva
    - banana