- name: printing loops
  hosts: local
  connection: local
  tasks:
  - name: loops
    ansible.builtin.debug:
      msg: "i love {{item}}"
  doop:
  - apple
  - grape
  - mango
  - orange
  - guvva
  - banana