- name: printing loops
  hosts: local
  connection: local
  tasks:
  - name: loops
    ansible.builtin.debug:
      name: "i love {{item.name}}"
      state: "taste is {{item.taste}}"
    loop:
    - { name: apple, taste: good}
    - {name: grape, taste: salty}
    - {name: mango, taste: sweet}
    - {name: orange, taste: sour}
    - {name: banana, taste: sweet}