- name: intsall the packages
  hosts: db_servers
  become: yes
  tasks:
  - name: installing the packages
    ansible.builtin.packages:
      name: '{{item.name}}'
      state: '{{item.state}}'
    loop:
    - {name: nginx, state: present}
    - {name: httpd, state: absent}