- name: printing filters
  hosts: db_servers
  tasks:
  - name: printing upper case
    vars:
      wishing: Hello Prakash
    ansible.builtin.debug:
      msg: "{{wishing | upper}}"

  - name: printing upper case
    vars:
      wishing: Hello Prakash
    ansible.builtin.debug:
      msg: "{{wishing | lower}}"
  
  - name: printing upper and lower
    vars:
      name: Prakash
      wishing: Hello
    ansible.builtin.debug:
      msg: "{{wishing | upper}} {{name | lower}}"

  - name: printing unique numbers
    vars:
      numbers: [1,2,3,5,4,5,4,3,2,1,33,2,13]
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

  - name: printing dict to items
    vars:
      course:
        name: testing
        time: 123
        mentor: ravi
    ansible.builtin.debug:
      msg: "{{course | dict2items}}"