- name: printing filters
  hosts: db_servers
  tasks:
  - name: printing upper case
    vars:
      wishing: Hello Prakash
    ansible.builtin.debug:
      msg: "{{wishing | upper}}"

  - name: printing upper case
    vars:
      wishing: Hello Prakash
    ansible.builtin.debug:
      msg: "{{wishing | lower}}"
  
  - name: printing upper and lower
    vars:
      name: Prakash
      wishing: Hello
    ansible.builtin.debug:
      msg: "{{wishing | upper}} {{name | lower}}"