- name: ping server
  hosts: localhost
  become: yes
  tasks:
  - name: pinging server
    ansible.builtin.debug:
      msg: "hello ansible"

- name: install nginx
  hosts: localhost
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: variables
  hosts: localhost
  become: yes
  vars:
    TIME: "120"
    AGE: "34"
  tasks:
  - name: adding vars
    ansible.builtin.debug:
      msg: "i don't have time {{TIME}}, But my age is {{AGE}}"